// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPJ4S4Lmsumem8DTDPdyoITQoiWUeZ_g',
    appId: '1:663175066500:web:588808802ea83b19eaa3d1',
    messagingSenderId: '663175066500',
    projectId: 'pittcampusfitness',
    authDomain: 'pittcampusfitness.firebaseapp.com',
    storageBucket: 'pittcampusfitness.firebasestorage.app',
    measurementId: 'G-PL43XRBV1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Jre8c5RlWMS3uV4f5-QXN9EH6mP4K_8',
    appId: '1:663175066500:android:21cca617064bfa66eaa3d1',
    messagingSenderId: '663175066500',
    projectId: 'pittcampusfitness',
    storageBucket: 'pittcampusfitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbA5AOhjDPCLI8FRtpoCLEy9cKyJZGCY8',
    appId: '1:663175066500:ios:dfaca606340085f9eaa3d1',
    messagingSenderId: '663175066500',
    projectId: 'pittcampusfitness',
    storageBucket: 'pittcampusfitness.firebasestorage.app',
    iosBundleId: 'com.example.mpx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbA5AOhjDPCLI8FRtpoCLEy9cKyJZGCY8',
    appId: '1:663175066500:ios:dfaca606340085f9eaa3d1',
    messagingSenderId: '663175066500',
    projectId: 'pittcampusfitness',
    storageBucket: 'pittcampusfitness.firebasestorage.app',
    iosBundleId: 'com.example.mpx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjPJ4S4Lmsumem8DTDPdyoITQoiWUeZ_g',
    appId: '1:663175066500:web:9e9dfe6903817378eaa3d1',
    messagingSenderId: '663175066500',
    projectId: 'pittcampusfitness',
    authDomain: 'pittcampusfitness.firebaseapp.com',
    storageBucket: 'pittcampusfitness.firebasestorage.app',
    measurementId: 'G-91P7DCCEN3',
  );

}